const testimonialsData = [
  {
    image: 'img/author-img1.png',
    name: 'Michael John',
    address: 'Local Austria',
    time: 'Today',
    textOne: 'The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met.My son delighted very much ljves to watch gouillas.Online zoo is one jf the ways to instill a love for animals.',
    textTwo: 'The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for',
  },
  {
    image: 'img/author-img2.jpg',
    name: 'Oskar Samborsky',
    address: 'Local Austria',
    time: 'Yesterday',
    textOne: 'Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas.',
    textTwo: 'The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met.My son delighted very much ljves to watch gouillas.Online zoo is one jf the ways to instill a love for',
  },
  {
    image: 'img/author-img4.jpg',
    name: 'Oska Samborska',
    address: 'Local Austria',
    time: 'Yesterday',
    textOne: 'Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas.',
    textTwo: 'The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.',
  },
  {
    image: 'img/author-img3.jpg',
    name: 'Fredericka Michelin',
    address: 'Local Austria',
    time: 'Yesterday',
    textOne: 'The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.',
    textTwo: 'The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met.',
  },
  {
    image: 'img/author-img5.jpg',
    name: 'Green Lantern',
    address: 'NY',
    time: 'Today',
    textOne: 'Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas.',
    textTwo: 'The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met.',
  },
  {
    image: 'img/author-img6.jpg',
    name: 'Anthony Edward "Tony" Stark',
    address: 'St. Petersburg',
    time: 'Yesterday',
    textOne: 'The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met.',
    textTwo: 'Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas.',
  },
  {
    image: 'img/author-img7.jpg',
    name: 'James Howlett',
    address: 'Bali, Denpasar',
    time: 'Yesterday',
    textOne: 'Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas.',
    textTwo: 'The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for',
  },
  {
    image: 'img/author-img8.jpg',
    name: 'Bruce Wayne',
    address: 'Gotham City',
    time: 'Today',
    textOne: 'The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for',
    textTwo: 'Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas.',
  },
  {
    image: 'img/author-img9.jpg',
    name: 'Peter Parker',
    address: 'NY',
    time: 'Yesterday',
    textOne: 'Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas.',
    textTwo: 'The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for',
  },
  {
    image: 'img/author-img10.jpg',
    name: 'Clark Kent',
    address: 'Krypton',
    time: 'Today',
    textOne: 'The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for',
    textTwo: 'Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas.',
  },
  {
    image: 'img/author-img11.jpg',
    name: 'Bruce Banner',
    address: 'Toronto',
    time: 'Yesterday',
    textOne: 'Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas.',
    textTwo: 'The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for animals.The best online zoo I\’ve met. My son delighted very much ljves to watch gouillas. Online zoo is one jf the ways to instill a love for',
  },
]

export default testimonialsData